# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Linux Build

on:
  push:
    branches: [dual]
  pull_request:
    branches: [dual]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      - name: PyInstaller
        run: |
          pyinstaller duobot.spec
          cp mainwindow.ui ./dist/duobot/
          cp config.json ./dist/duobot/
      - name: Archive built module
        uses: actions/upload-artifact@v3
        if: success()
        with:
          name: duobot_linux
          path: ./dist/duobot
